# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  matrix:
    - nodejs_version: "6"

# scripts that run after cloning repository
install:
  # to run script as a PowerShell command prepend it with ps:
  - ps: Install-Product node $env:nodejs_version
  # batch commands start from cmd:
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build: off

